PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX krr: <http://www.semanticweb.org/hunaizanaveed/ontologies/2025/11/krr_project#>

INSERT { ?s rdf:type krr:DepressiveSpectrum }
WHERE {
    ?session krr:hasSessionStudent ?s .
    # Explicit mapping to DepressiveSpectrum via concept_mapper
    ?session krr:hasEvidence ?e .
    ?e rdf:type krr:DepressiveSpectrum .
}
